title: "Assigment - Naive Bayes DIY"
author:
  - Evert-Jan - Author
  - Chihiro - Reviewer
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
   html_notebook:
    toc: true
    toc_depth: 2

## setup

```{r}
library(tidyverse)
library(tm)
library(caret)
library(wordcloud)
library(e1071)
```

## data understanding

```{r}
url <- "https://raw.githubusercontent.com/HAN-M3DM-Data-Mining/data-mining-s2y2122-Evert-JanH/master/datasets/NB-fakenews.csv"

rawDF <- read_csv(url)
head(rawDF)
```

```{r}
summary(rawDF)
```

```{r}
Table(rawDF$label)
```

```{r}
rawDF$label <- rawDF$label %>% factor %>% relevel ("1")
class(rawDF$label)
```

```{r}
fakenews <- rawDF %>% filter(label == "1")
news <- rawDF %>% filter(label == "0")



wordcloud(fakenews$text, max.words = 20, scale = c(4, 0.8), colors= c("indianred1","indianred2","indianred3","indianred"))
wordcloud(news$text, max.words = 20, scale = c(4, 0.8), colors= c("lightsteelblue1","lightsteelblue2","lightsteelblue3","lightsteelblue"))
```

## Data Preperation
```{r}
rawCorpus <- Corpus(VectorSource(rawDF$text))
inspect(rawCorpus[1:3])
```
```{r}
toSpace <- content_transformer(function(x, pattern) {return (gsub(pattern, ' ', x))})
```


```{r}
cleanCorpus <- rawCorpus %>% tm_map(to lower) %>% tm_map(removeNumbers)
```

```{r}
cleanCorpus <- cleanCorpus %>% tm_map(tolower) %>% tm_map(removeWords, stopwords()) %>% tm_map(removePunctuation) %>% tm_map(toSpace, "-") %>% tm_map(toSpace, "”")  %>% tm_map(toSpace, "“") %>% tm_map(toSpace, "’s") %>% tm_map(toSpace, " —")
```

```{r}
cleanCorpus <- cleanCorpus %>% tmmap(stripWhitespace)
```

```{r}
tibble(Raw = rawCorpus$content[1:3], Clean = cleanCorpus$content[1:3])
```
```{r}
cleanDTM <- cleanCorpus %>% DocumentTermmatrix
inspect(cleanDTM)
```
```{r}
set.seed(1234)
trainIndex <- createDataPartition(rawDF$label, p = .75,
                                  list = FALSE,
                                  times = 1)
head(trainIndex)
```

```{r}
trainDF <- rawDF[trainIndex, ]

testDF <- rawDF[-trainIndex, ]
```

```{r}
trainCorpus <- cleanCorpus[trainIndex]
testCorpus <- cleanCorpus[-trainIndex]
trainDTM <- cleanDTM[trainIndex, ]
testDTM <- cleanDTM[-trainIndex, ]
```

```{r}
freqWords <- trainDTM %>% findFreqTerms(225)
trainDTM <-  DocumentTermMatrix(trainCorpus, list(dictionary = freqWords))
testDTM <-  DocumentTermMatrix(testCorpus, list(dictionary = freqWords))
```

```{r}
convert_counts <- function(x) {
  x <- ifelse(x > 0, 1, 0) %>% factor(levels = c(0,1), labels = c("No", "Yes"))
}



nColsDTM <- dim(trainDTM)[2]
trainDTM <- apply(trainDTM, MARGIN = 2, convert_counts)
testDTM <- apply(testDTM, MARGIN = 2, convert_counts)



head(trainDTM[,1:10])
```

## Modeling

```{r}
nbayesModel <-  naiveBayes(trainDTM, trainDF$label, laplace = 0)
```

## Evaluation and Deployment
```{r}
predVec <- predict(nbayesModel, testDTM)
confusionMatrix(predVec, testDF$label, positive = "1", dnn = c("Prediction", "True"))
```

